# Generated by Django 4.2.4 on 2023-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_profile',
            name='store_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
