# Generated by Django 4.2.4 on 2023-10-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0002_seller_profile_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_profile',
            name='srating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
