# Generated by Django 4.2.4 on 2023-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0003_seller_profile_srating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_profile',
            name='srating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
