# Generated by Django 4.2.4 on 2023-08-09 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variation',
            name='product_image_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
