# Generated by Django 4.2.4 on 2023-08-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0005_alter_product_product_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.product'),
        ),
    ]
