# Generated by Django 4.2.4 on 2023-08-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0006_product_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.product_variation'),
        ),
    ]
