# Generated by Django 4.2.4 on 2023-08-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0008_alter_product_image_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_id',
        ),
        migrations.RemoveField(
            model_name='product_variation',
            name='product_image_id',
        ),
    ]
