# Generated by Django 4.2.4 on 2023-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
        ('po_app', '0010_order_shippingaddress_order_details_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.seller_profile'),
        ),
    ]
