# Generated by Django 4.2.4 on 2023-08-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0011_alter_order_details_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flashsale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
