# Generated by Django 4.2.4 on 2023-09-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0016_alter_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
