# Generated by Django 4.2.4 on 2023-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0019_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
