# Generated by Django 4.2.4 on 2023-09-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0020_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='order',
            new_name='order_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
