# Generated by Django 4.2.4 on 2023-09-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0021_rename_order_order_details_order_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_qty',
        ),
    ]
