# Generated by Django 4.2.4 on 2023-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0023_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
