# Generated by Django 4.2.4 on 2023-09-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0026_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='variation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po_app.product_variation'),
        ),
    ]
