# Generated by Django 4.2.4 on 2023-09-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0027_order_details_variation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='retail_price',
        ),
    ]
