# Generated by Django 4.2.4 on 2023-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0031_product_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
