# Generated by Django 4.2.4 on 2023-09-20 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0032_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
