# Generated by Django 4.2.4 on 2023-09-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0033_order_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_details',
            new_name='od_array',
        ),
    ]
