# Generated by Django 4.2.4 on 2023-09-21 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0036_alter_order_details_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
