# Generated by Django 4.2.4 on 2023-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0037_order_seller_id_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='totalqty',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
    ]
