# Generated by Django 4.2.4 on 2023-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0038_alter_product_totalqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
