# Generated by Django 4.2.4 on 2023-09-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_size_attr_color_attr'),
        ('po_app', '0039_alter_order_details_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.color_attr'),
        ),
        migrations.AlterField(
            model_name='product_variation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.size_attr'),
        ),
    ]
