# Generated by Django 4.2.4 on 2023-09-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_product_attr_remove_color_attr_cateogry_and_more'),
        ('po_app', '0040_alter_product_variation_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product_variation',
            name='size',
        ),
        migrations.AddField(
            model_name='product_variation',
            name='p_attr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.product_attr'),
        ),
    ]
