# Generated by Django 4.2.4 on 2023-09-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0042_remove_product_variation_p_attr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variation',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
