# Generated by Django 4.2.4 on 2023-10-03 11:00

from django.db import migrations, models
import po_app.helper


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0043_alter_product_variation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='rmbg_photo',
            field=models.ImageField(blank=True, null=True, upload_to=po_app.helper.RandomFileName('test/')),
        ),
    ]
