# Generated by Django 4.2.4 on 2023-10-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0044_product_image_rmbg_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='rmbg_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
