# Generated by Django 4.2.4 on 2023-10-05 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0045_remove_product_image_rmbg_photo_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hightlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
