# Generated by Django 4.2.4 on 2023-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0047_rename_hightlights_product_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sdes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
