# Generated by Django 4.2.4 on 2023-10-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0049_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oservices',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wservices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po_app.services'),
        ),
    ]
