# Generated by Django 4.2.4 on 2023-10-12 13:04

from django.db import migrations
import django_resized.forms
import po_app.helper


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0051_product_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=0.5, size=[500, 300], upload_to=po_app.helper.RandomFileName('product_image/')),
        ),
    ]
