# Generated by Django 4.2.4 on 2023-10-15 14:42

from django.db import migrations, models
import django_advance_thumbnail.fields
import django_resized.forms
import po_app.helper


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0052_alter_product_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ldes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=1, size=[1024, 768], upload_to=po_app.helper.RandomFileName('product_image/')),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to=po_app.helper.RandomFileName('thumbnail_image/')),
        ),
    ]
