# Generated by Django 4.2.4 on 2023-10-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0053_product_ldes_alter_product_image_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variation',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
