# Generated by Django 4.2.4 on 2023-10-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0054_product_variation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variation',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
