# Generated by Django 4.2.4 on 2023-10-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0056_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='oder',
            new_name='order',
        ),
    ]
