# Generated by Django 4.2.4 on 2023-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0057_rename_oder_tracking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='tracking_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
