# Generated by Django 4.2.4 on 2023-10-31 02:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0058_tracking_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
