# Generated by Django 4.2.4 on 2023-10-31 02:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0059_order_tracking_id_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
    ]
