# Generated by Django 4.2.4 on 2023-11-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0012_rating_comment_createdat'),
        ('seller_app', '0006_alter_image_folder_img_id'),
        ('po_app', '0060_alter_order_tracking_id_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer_profile')),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.seller_profile')),
                ('tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.tracking')),
                ('variation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po_app.product_variation')),
            ],
        ),
    ]
