# Generated by Django 4.2.4 on 2023-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0006_alter_image_folder_img_id'),
        ('customer_app', '0012_rating_comment_createdat'),
        ('po_app', '0061_trackingdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackingDetails',
            new_name='Tracking_Details',
        ),
    ]
