# Generated by Django 4.2.4 on 2023-11-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0062_rename_trackingdetails_tracking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_details',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.shippingaddress'),
        ),
    ]
