# Generated by Django 4.2.4 on 2023-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0063_tracking_details_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_details',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
