# Generated by Django 4.2.4 on 2023-12-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0064_tracking_details_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
