# Generated by Django 4.2.4 on 2023-09-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0017_remove_product_tags'),
        ('customer_app', '0003_alter_customer_profile_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer_profile')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.product')),
            ],
        ),
    ]
