# Generated by Django 4.2.4 on 2023-09-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_alter_customer_profile_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_comment',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
