# Generated by Django 4.2.4 on 2023-10-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0011_alter_rating_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_comment',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
