# Generated by Django 4.2.4 on 2023-09-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_product_attr_remove_color_attr_cateogry_and_more'),
        ('po_app', '0041_remove_product_variation_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color_Attr',
        ),
        migrations.DeleteModel(
            name='Size_Attr',
        ),
    ]
