export const ALL_NESTED_CATEGORY_REQUEST = 'ALL_NESTED_CATEGORY_REQUEST'
export const ALL_NESTED_CATEGORY_SUCCESS = 'ALL_NESTED_CATEGORY_SUCCESS'
export const ALL_NESTED_CATEGORY_FAIL = 'ALL_NESTED_CATEGORY_FAIL'



export const FLASH_SALE_REQUEST = 'FLASH_SALE_REQUEST'
export const FLASH_SALE_SUCCESS = 'FLASH_SALE_SUCCESS'
export const FLASH_SALE_FAIL = 'FLASH_SALE_FAIL'


export const TOP_CATEGORY_REQUEST = 'TOP_CATEGORY_REQUEST'
export const TOP_CATEGORY_SUCCESS = 'TOP_CATEGORY_SUCCESS'
export const TOP_CATEGORY_FAIL = 'TOP_CATEGORY_FAIL'


export const DASH_PRODUCT_REQUEST = "DASH_PRODUCT_REQUEST"
export const DASH_PRODUCT_SUCCESS = "DASH_PRODUCT_SUCCESS"
export const DASH_PRODUCT_FAIL = "DASH_PRODUCT_FAIL"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL"

export const SELLER_PRO_SHUFFLE_REQUEST = "SELLER_PRO_SHUFFLE_REQUEST"
export const SELLER_PRO_SHUFFLE_SUCCESS = "SELLER_PRO_SHUFFLE_SUCCESS"
export const SELLER_PRO_SHUFFLE_FAIL = "SELLER_PRO_SHUFFLE_FAIL"

export const RELATED_ITEM_REQUEST = "RELATED_ITEM_REQUEST"
export const RELATED_ITEM_SUCCESS = "RELATED_ITEM_SUCCESS"
export const RELATED_ITEM_FAIL = "RELATED_ITEM_FAIL"



export const CATEGORY_RELATED_ITEM_REQUEST = "CATEGORY_RELATED_ITEM_REQUEST"
export const CATEGORY_RELATED_ITEM_SUCCESS = "CATEGORY_RELATED_ITEM_SUCCESS"
export const CATEGORY_RELATED_ITEM_FAIL = "CATEGORY_RELATED_ITEM_FAIL"
export const CATEGORY_TOTAL = "CATEGORY_TOTAL"
export const BRAND_REQUEST = 'BRAND_REQUEST'




export const CUSTOMER_INFO_REQUEST = "CUSTOMER_INFO_REQUEST"
export const CUSTOMER_INFO_SUCCESS = "CUSOTMER_INFO_SUCCESS"
export const CUSTOMER_INFO_FAIL = "CUSOTMER_INFO_FAIL"


export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"


export const SHIPPING_ADDRESS_REQUEST  = "SHIPPING_ADDRESS_REQUEST"
export const SHIPPING_ADDRESS_SUCCESS  = "SHIPPING_ADDRESS_SUCCESS"
export const SHIPPING_ADDRESS_FAIL  = "SHIPPING_ADDRESS_FAIL"


export const ORDER_ITEM_SAVE = "ORDER_ITEM_SAVE"
export const ORDER_ITEM_SAVE_FAIL  = "ORDER_ITEM_SAVE_FAIL"


export const FILTER_DATA ="FITLER_DATA"